### ISSUE TITLE
Can't resolve ../../../pre/tools

### ISSUE THREAD

**Issue by erentar** [NASA-AMMOS/MMGIS#21]
steps taken:
```
git clone https://github.com/NASA-AMMOS/MMGIS
cd MMGIS
cp sample.env .env
nano .env
npm install
npm start
```
result:
```
Failed to compile.

./src/essence/Basics/Test_/Test_.js
Module not found: Can't resolve '../../../pre/tools' in 'MMGIS/src/essence/Basics/Test_'
```

**Comment by tariqksoliman** [comment]
Hi. So `/src/pre/tools.js` is a file that is automatically generated on runtime and which enables tools to behave as plugins. 

`npm start` should output the following logs (you may need to scroll up since the console jumps):
 ```
 info   Successfully updated tool definitions.
 info   Successfully updated source tool configurations.
 ```

Right now this tool function has a reliance on the Postgres DB so it's likely that it didn't generate because the database isn't set up quite right.

I've updated `master` with a few fixes regarding this along with a placeholding tools.js script. That may get you further along but, again, the database is critical.

**Comment by erentar** [comment]
My apologies, PostGIS setup had failed and i had not noticed. I no longer have the problem after recreating the database.
Thank you for your attention
