### ISSUE TITLE
Function of the bounding box

### ISSUE THREAD

**Issue by erentar** [NASA-AMMOS/MMGIS#29]
I am using gdal2tiles.py to render the tiles, which does not georeference the tiles in the path, but does so through the bounding box in tilemapresource.xml.
Right now, if i load the tilemapresource.xml for the rendered tiles, it has the property bounding box indicating where the tiles should fit into. For some reason, MMGIS only draws the tiles that end up inside the bounding box.
If i the bounding box is removed, all of the tiles are drawn but the tiles span the entire planet, which should not be the case.

The problem could be caused by a different bug, but i suspect that MMGIS does not read bounding box as a georeference but as a limit to stop drawing the tiles.

**Comment by fcalef** [comment]
If you're working with Earth-based datasets, make sure you're using the '-p mercator' option (this should be the default) and your data is in Mercator projection. Otherwise, you can use the raster2tiles.py script to convert the dataset (assuming it has a projection) on the fly:
https://github.com/NASA-AMMOS/MMGIS/tree/master/auxiliary/rasterstotiles

It is true that the bounding box is meant to have MMGIS only draw tiles within that bound of the dataset. If you set that bounds to be smaller, it will only draw the tiles within that extent.

**Comment by erentar** [comment]
rasters2tiles.py works✅
thanks!
