### ISSUE TITLE
access to vector layer in viewer

### ISSUE THREAD

**Issue by miladadp** [NASA-AMMOS/MMGIS#32]
hi.i have an issue  accessing  to vector layers in viewer. vector layer section is kind of reddish and when i put cursor on the layers it shows "no waiting sign" sort of thing. i am very naive with whole MMGIS but really interseted to work with it. i would really appreciate if you walk me  through the process of  adding vector layers and basemaps to my project just like perseverance interactive map.

![Screenshot (1142)](https://user-images.githubusercontent.com/80363226/110851397-376da480-82c6-11eb-8ef0-c410ad422f79.png)

**Comment by fcalef** [comment]
Hi! Apologies, been on Marstime. Looks like you made a lot of progress in getting MMGIS running!

The vector layers are red because they can't find the files. Check under the 'Missions/Test/Layers' folder and see if any of the files are there. If they are, you should go to the Configuration page and check whether the Layers are point to the correct location, which should be `Layers/filename.json' where 'filename' is the name of the above layers. As for the 'Tile with DEM' layer, you can check it in the same way.

Check the wiki here about the Configuration page: https://github.com/NASA-AMMOS/MMGIS/blob/master/docs/pages/markdowns/Configure.md

Check out the wiki for information about configuring Layers: https://github.com/NASA-AMMOS/MMGIS/blob/master/docs/pages/markdowns/Layers_Tab.md

As for adding in other datasets, you can generate raster basemaps using the raster2tiles.py program:
https://github.com/NASA-AMMOS/MMGIS/tree/master/auxiliary/rasterstotiles

For vector data, you should use GDAL (www.gdal.org). Specifically, the ogr2ogr program which can convert shapefiles (and others) to GeoJSON format, which is what MMGIS uses. In addition, the GeoJSON needs to have coordinates in longitude and latitude. If you have a shapefile that was already in longitude and latitude, you should run the GDAL command like this:

`ogr2ogr output.json input.shp`

or if the shapefile (assuming something on Mars) is in projected units (e.g. Equidistant Cylindrical meters), you'd need to convert them to longitude and latitude:

`ogr2ogr -t_srs "+proj=longlat +R=3396190 +no_defs" output.json input.shp`

The output would look something like the Perseverance rover waypoints:
https://mars.nasa.gov/mmgis-maps/M20/Layers/json/M20_waypoints.json

and rover traverse:
https://mars.nasa.gov/mmgis-maps/M20/Layers/json/M20_traverse.json

For the Perseverance rover, you can grab some basemap here:
https://astrogeology.usgs.gov/maps/mars-2020-jezero-crater-landing-site-controlled-orthomosaics

For example, you could make a new mission called "Perseverance" in the configuration, then make a layer called 'Basemap', 'Traverse', and 'Waypoints'. You can use the files above for the latter two layers, but for the basemap you can tile one of the Perseverance ones from above:
python raster2tiles.py JEZ_ctx_B_soc_008_orthoMosaic_6m_Eqc_latTs0_lon0.tif
(data from https://planetarymaps.usgs.gov/mosaic/mars2020_trn/CTX/JEZ_ctx_B_soc_008_orthoMosaic_6m_Eqc_latTs0_lon0.tif)

Check back in if you have success or have more questions.

**Comment by miladad8** [comment]
thank you very much

**Comment by miladadp** [comment]
thank you very much for your kindness and help
